# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GetFeishuDocs < Formula
  desc "CLI for exporting Feishu documents into stable local deliverables."
  homepage "https://github.com/Wangnov/get-feishu-docs"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wangnov/get-feishu-docs/releases/download/v0.2.0/get-feishu-docs_0.2.0_darwin_amd64.tar.gz"
      sha256 "3967fc82c3c58ad99d7e6b6b7409657741a2c6d485f3b7d96f8848a7a7a3912e"

      define_method(:install) do
        bin.install "get-feishu-docs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wangnov/get-feishu-docs/releases/download/v0.2.0/get-feishu-docs_0.2.0_darwin_arm64.tar.gz"
      sha256 "ae08acd73374414d0e6e22fad477d19e4a4d8e83aff50f1813c53b823d5056b1"

      define_method(:install) do
        bin.install "get-feishu-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wangnov/get-feishu-docs/releases/download/v0.2.0/get-feishu-docs_0.2.0_linux_amd64.tar.gz"
      sha256 "ada8b51756510e518ef94b1d4607c3e2edea09385d96d802ffe36b4af22debbf"
      define_method(:install) do
        bin.install "get-feishu-docs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wangnov/get-feishu-docs/releases/download/v0.2.0/get-feishu-docs_0.2.0_linux_arm64.tar.gz"
      sha256 "44a3004bd1e98fa800b9f889a9009fda8f85e2f218de5a328a104b2282f2839f"
      define_method(:install) do
        bin.install "get-feishu-docs"
      end
    end
  end

  test do
    system "#{bin}/get-feishu-docs", "--version"
  end
end
